[features]
seeds = false
skip-lint = false
[programs.localnet]
zk_battleship = "5Jt2pEktgDMHWpy6aEUVx5Kt7XfLKpA1oahAyoLA7i98"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/mahmoud/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"
